// Auto-generated by scripts/gen-svgs-index.js
// Do not edit manually

import Svg0 from './about-filled.svg'
import Svg1 from './about-outline.svg'
import Svg2 from './email.svg'
import Svg3 from './github.svg'
import Svg4 from './juejin.svg'
import Svg5 from './music.svg'
import Svg6 from './pen.svg'
import Svg7 from './play.svg'
import Svg8 from './projects-filled.svg'
import Svg9 from './projects-outline.svg'
import Svg10 from './scroll-filled.svg'
import Svg11 from './scroll-outline.svg'
import Svg12 from './share-filled.svg'
import Svg13 from './share-outline.svg'
import Svg14 from './short-line.svg'
import Svg15 from './top.svg'
import Svg16 from './website-filled.svg'
import Svg17 from './website-outline.svg'

export type SvgComponent = React.ComponentType<React.SVGProps<SVGSVGElement>>

export const svgItems: { key: string; Component: SvgComponent }[] = [
	{ key: './about-filled.svg', Component: Svg0 },
	{ key: './about-outline.svg', Component: Svg1 },
	{ key: './email.svg', Component: Svg2 },
	{ key: './github.svg', Component: Svg3 },
	{ key: './juejin.svg', Component: Svg4 },
	{ key: './music.svg', Component: Svg5 },
	{ key: './pen.svg', Component: Svg6 },
	{ key: './play.svg', Component: Svg7 },
	{ key: './projects-filled.svg', Component: Svg8 },
	{ key: './projects-outline.svg', Component: Svg9 },
	{ key: './scroll-filled.svg', Component: Svg10 },
	{ key: './scroll-outline.svg', Component: Svg11 },
	{ key: './share-filled.svg', Component: Svg12 },
	{ key: './share-outline.svg', Component: Svg13 },
	{ key: './short-line.svg', Component: Svg14 },
	{ key: './top.svg', Component: Svg15 },
	{ key: './website-filled.svg', Component: Svg16 },
	{ key: './website-outline.svg', Component: Svg17 }
]



export function BilibiliOutline(props: React.SVGProps<SVGSVGElement>) {
  // 注意这里添加了 fill="currentColor"，让图标颜色跟随文字
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
      <rect x="4" y="6" width="16" height="12" rx="2" />
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <path d="M9 14c1.5.5 3 .5 4.5 0" />
      <path d="M9 10h.01" />
      <path d="M15 10h.01" />
    </svg>
  )
}


export function BilibiliFilled(props: React.SVGProps<SVGSVGElement>) {
  // 注意这里是填充模式，stroke="none" 且 fill="currentColor"
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" stroke="none" {...props}>
      <path d="M18 6H6a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2zM8 2v4h2V2H8zm6 0v4h2V2h-2zM9 14c1.5.5 3 .5 4.5 0" />
      <circle cx="9" cy="10" r="1.5" fill="white" />
      <circle cx="15" cy="10" r="1.5" fill="white" />
    </svg>
  )
}
